apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: lieutenant-api
  app.kubernetes.io/part-of: project-syn
images:
  - name: docker.io/projectsyn/lieutenant-api
    newTag: v0.8.0
resources:
  - deployment.yaml
  - role_binding.yaml
  - role.yaml
  - service_account.yaml
  - service.yaml
