apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lieutenant-api
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - syn.tools
    resources:
      - clusters
    verbs:
      - list
  - apiGroups:
      - syn.tools
    resources:
      - clusters/status
    verbs:
      - update
