apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: lieutenant-api
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - secrets
  verbs:
  - get
- apiGroups:
  - syn.tools
  resources:
  - clusters
  verbs:
  - list
- apiGroups:
  - syn.tools
  resources:
  - clusters/status
  verbs:
  - update
