= Deployment

The Lieutenant API is meant to be deployed on a Kubernetes cluster. It needs to be the same cluster it uses as a back end to store the CRs.

The xref:lieutenant-operator::index.adoc[Lieutenant Operator] needs to be deployed on the cluster and with it the accompanying CRDs. Make sure the operator watches objects in the namespace where the API is being deployed.

You can find a https://kustomize.io[Kustomize] setup for a deployment in the "deploy/" folder. A role and service account will be created for the API. The `Cluster` and `Tenant` CRs will be stored in the same namespace as the API is deployed.

[source,shell]
----
kubectl create ns $namespace

kubectl -n $namespace apply -k deploy/
----


== Configuration

See the xref:references/configuration.adoc[Configuration] reference for available configuration options.

== GitLab

Currently the API creates `GitRepo` objects with a hard coded reference for the GitLab API credentials secret. This is subject to change and will be configurable on a per tenant basis. Make sure a secret with the name `vshn-gitlab` exists in the API's namespace. The secret needs the following keys:

* `endpoint` GitLab API endpoint (`https://gitlab.com`)
* `token` GitLab API token to use
* `hostKeys` SSH keys of GitLab (in known_hosts format)



IMPORTANT: Currently the groups and subgroups for git repositories aren't created automatically and need to exist. The GitLab user in the group should have at least `Maintainer` privileges to be able to create, update and delete repositories.
